WIN_WIDTH = 900
WIN_HEIGHT = 600

FPS = 60

LOADINGSCREENSPEED = 30 #higher the number, lower the speed
LOADINGSCREENDELAY = 1 #higher the numnber, more the delay

PLAYERSPEED = 4 #higher the number,slower the player
FIGHTSPEED=6
PLAYERVELOCITY = 3

ENEMYSPEED=4
ENEMYVELOCITY = 3

LOADINGSCREENDONEFADEOUT = 1.5

SIDE=90